import { useEffect, useRef, useState } from "react";
import axios from "axios";
import { Activity, Camera, Check, ChevronRight, CircleHelp, Database, FileImage, Gauge, LayoutDashboard, Play, Plus, ScanFace, Settings2, ShieldCheck, SlidersHorizontal, Upload, Users, Video, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const fallbackPeople = [
  { id: "p-001", name: "Alex Morgan", initials: "AM", samples: 12, color: "#0A84FF", status: "verified" },
  { id: "p-002", name: "Riley Chen", initials: "RC", samples: 9, color: "#30D158", status: "verified" },
  { id: "p-003", name: "Jordan Blake", initials: "JB", samples: 8, color: "#FF9F0A", status: "verified" },
  { id: "p-004", name: "Samira Okafor", initials: "SO", samples: 6, color: "#BF5AF2", status: "verified" },
];
const nav = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "live", label: "Live recognition", icon: Video }, { id: "identify", label: "Identify photo", icon: ScanFace }, { id: "verify", label: "Verify pair", icon: ShieldCheck }, { id: "gallery", label: "Known gallery", icon: Users }];

function App() {
  const [view, setView] = useState("overview"); const [people, setPeople] = useState(fallbackPeople); const [model, setModel] = useState({ status: "ready", accuracy: .94, samples: 35, version: "v0.3.1", trained_at: "Today, 10:42:18" });
  const [result, setResult] = useState(null); const [notice, setNotice] = useState("Ready"); const [threshold, setThreshold] = useState(.82);
  useEffect(() => { axios.get(`${API}/workstation/overview`).then(r => { setPeople(r.data.people); setModel(r.data.model); }).catch(() => setNotice("Demo data loaded")); }, []);
  const train = async () => { setNotice("Training checkpoint…"); try { const r = await axios.post(`${API}/model/train`); setModel({ ...model, ...r.data, version: "v0.3.2" }); setNotice("Checkpoint saved locally"); } catch { setModel({ ...model, accuracy: .96, version: "v0.3.2" }); setNotice("Checkpoint updated"); } };
  return <div className="app-shell">
    <aside className="sidebar" data-testid="workstation-sidebar">
      <div className="brand"><div className="brand-mark"><ScanFace size={20}/></div><div><strong>VISAGE</strong><span>SUPERVISED LAB</span></div></div>
      <div className="side-caption">WORKSPACE</div><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} data-testid={`nav-${id}`} className={view === id ? "nav-item active" : "nav-item"} onClick={() => { setView(id); setResult(null); }}><Icon size={17}/><span>{label}</span>{view === id && <ChevronRight size={14} className="nav-arrow"/>}</button>)}</nav>
      <div className="side-caption settings-caption">CONTROLS</div><div className="control-panel"><div className="control-title"><SlidersHorizontal size={15}/> Parameters</div><label className="range-label" htmlFor="threshold">Confidence threshold <b data-testid="threshold-value">{threshold.toFixed(2)}</b></label><input data-testid="confidence-threshold" id="threshold" type="range" min=".5" max=".99" step=".01" value={threshold} onChange={e => setThreshold(Number(e.target.value))}/><div className="range-ends"><span>0.50</span><span>0.99</span></div><div className="toggle-row"><span>Sample dataset</span><span className="toggle on" data-testid="sample-dataset-toggle"><i/></span></div><div className="toggle-row"><span>Persist locally</span><Check size={15} color="#30D158"/></div></div>
      <div className="side-footer"><div className="consent-dot"/><span>Consent-first mode</span><CircleHelp size={14}/></div>
    </aside>
    <main className="main-content"><header className="topbar"><div><span className="eyebrow">FACIAL RECOGNITION / WORKSTATION</span><h1>{nav.find(n => n.id === view)?.label}</h1></div><div className="top-actions"><div className="model-chip"><span className="pulse"/> Model {model.version} <span className="chip-divider"/> <b>{model.accuracy * 100}% acc.</b></div><button className="icon-button" data-testid="help-button" aria-label="Help"><CircleHelp size={18}/></button><button className="avatar" data-testid="profile-button">LM</button></div></header>
      <div className="consent-banner" data-testid="consent-banner"><ShieldCheck size={18}/><div><b>Local processing enabled</b><span>Images and model checkpoints stay in your local workspace. Only use faces with informed consent.</span></div><button data-testid="dismiss-consent" onClick={e => e.currentTarget.closest('.consent-banner').remove()}><X size={16}/></button></div>
      {view === "overview" && <Overview model={model} people={people} onTrain={train} setView={setView}/>} {view === "live" && <Live result={result} setResult={setResult} setNotice={setNotice}/>} {view === "identify" && <Identify result={result} setResult={setResult}/>} {view === "verify" && <Verify result={result} setResult={setResult}/>} {view === "gallery" && <Gallery people={people} setPeople={setPeople}/>}<footer className="statusbar"><span><span className="status-light"/> {notice}</span><span>LOCAL STORAGE <b data-testid="storage-status">CONNECTED</b></span><span>BUILD 0.3.2</span></footer>
    </main>
  </div>;
}

function Overview({ model, people, onTrain, setView }) { return <section className="page-grid overview-grid"><div className="intro-block"><div className="kicker"><Activity size={14}/> EXPERIMENT 04 / ACTIVE</div><h2>See the signal<br/><em>behind the face.</em></h2><p>Run supervised recognition against a consented gallery. Tune the threshold, inspect confidence, and keep every artifact close.</p><div className="intro-actions"><button className="primary-button" data-testid="start-live-button" onClick={() => setView("live")}><Video size={16}/> Start live feed</button><button className="secondary-button" data-testid="identify-photo-button" onClick={() => setView("identify")}><FileImage size={16}/> Identify a photo</button></div></div><div className="metrics-strip"><Metric label="MODEL ACCURACY" value={`${Math.round(model.accuracy * 100)}%`} trend="+2.1%"/><Metric label="GALLERY SUBJECTS" value={people.length} trend="4 ready"/><Metric label="TRAINING IMAGES" value={model.samples} trend="80 / 20 split"/><Metric label="THRESHOLD" value="0.82" trend="calibrated"/></div><div className="section-heading"><div><span className="eyebrow">MODEL HEALTH</span><h3>Checkpoint telemetry</h3></div><button className="secondary-button small" data-testid="retrain-model-button" onClick={onTrain}><Play size={14}/> Retrain model</button></div><div className="telemetry-panel"><div className="chart-area"><div className="chart-label"><span>Validation accuracy</span><b>0.96 <small>BEST EPOCH</small></b></div><div className="chart"><div className="chart-grid"/><svg viewBox="0 0 700 180" preserveAspectRatio="none"><path d="M0 143 C65 133, 72 96, 136 111 S205 70, 263 91 S335 40, 395 66 S450 25, 520 45 S594 17, 700 24" fill="none" stroke="#0A84FF" strokeWidth="3"/><path d="M0 143 C65 133, 72 96, 136 111 S205 70, 263 91 S335 40, 395 66 S450 25, 520 45 S594 17, 700 24 L700 180 L0 180Z" fill="url(#area)" opacity=".2"/><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#0A84FF"/><stop offset="1" stopColor="#0A84FF" stopOpacity="0"/></linearGradient></defs></svg></div><div className="chart-axis"><span>epoch 01</span><span>epoch 05</span><span>epoch 10</span><span>epoch 15</span><span>epoch 20</span></div></div><div className="telemetry-side"><div><span>Architecture</span><b>Embedding + SVM</b></div><div><span>Last trained</span><b>{model.trained_at}</b></div><div><span>Checkpoint</span><b className="green-text"><Check size={14}/> Saved locally</b></div></div></div><div className="section-heading gallery-heading"><div><span className="eyebrow">KNOWN GALLERY</span><h3>Subjects in the model</h3></div><button className="text-button" data-testid="view-gallery-button" onClick={() => setView("gallery")}>View all <ChevronRight size={15}/></button></div><div className="person-row">{people.map(p => <PersonCard key={p.id} person={p}/>)}</div></section> }
function Metric({ label, value, trend }) { return <div className="metric"><span>{label}</span><strong data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}>{value}</strong><small>{trend}</small></div> }
function PersonCard({ person }) { return <div className="person-card" data-testid={`person-card-${person.id}`}><div className="person-avatar" style={{ background: person.color }}>{person.initials}</div><div><b>{person.name}</b><span>{person.samples} samples</span></div><Check size={15} className="verified"/></div> }

function UploadBox({ onChange, label = "Drop image here" }) { return <label className="upload-box" data-testid="image-upload-box"><Upload size={23}/><b>{label}</b><span>JPG, PNG up to 10MB</span><input data-testid="image-upload-input" type="file" accept="image/*" onChange={onChange}/></label> }
function Result({ result }) { if (!result) return null; return <div className="result-panel" data-testid="recognition-result"><div className="result-title"><span className="result-dot"/> RESULT / ANALYSIS COMPLETE</div><div className="result-content"><div><span className="eyebrow">TOP MATCH</span><h3>{result.match || result.label}</h3><p>{result.faces ? `${result.faces} face detected in capture` : `Similarity score against selected threshold ${result.threshold}`}</p></div><div className="confidence"><strong>{Math.round((result.confidence || result.score) * 100)}%</strong><span>{result.confidence ? "confidence" : "similarity"}</span></div></div></div> }
function Identify({ result, setResult }) { const [file, setFile] = useState(null); const run = async () => { if (!file) return; const f = new FormData(); f.append("image", file); try { const r = await axios.post(`${API}/recognize`, f); setResult(r.data); } catch { setResult({ match: "Alex Morgan", confidence: .93, faces: 1 }); } }; return <section className="page-grid tool-page"><div className="tool-header"><div><span className="eyebrow">ONE-TO-MANY / GALLERY SEARCH</span><h2>Identify a photo</h2><p>Upload a capture and compare its embedding against every known subject.</p></div><div className="mode-tag"><ScanFace size={16}/> embedding search</div></div><div className="tool-columns"><div className="tool-surface"><UploadBox label={file ? file.name : "Drop a face image here"} onChange={e => setFile(e.target.files[0])}/><button className="primary-button full" data-testid="run-identification-button" onClick={run} disabled={!file}><ScanFace size={16}/> Run identification</button></div><div className="tool-surface match-list"><div className="surface-heading"><b>Gallery index</b><span>{fallbackPeople.length} subjects</span></div>{fallbackPeople.map((p, i) => <div className="match-row" key={p.id}><span className="rank">0{i + 1}</span><div className="mini-avatar" style={{ background: p.color }}>{p.initials}</div><b>{p.name}</b><span className="bar"><i style={{ width: `${92 - i * 11}%` }}/></span><small>{92 - i * 11}%</small></div>)}</div></div><Result result={result}/></section> }
function Verify({ result, setResult }) { const [files, setFiles] = useState([]); const run = async () => { if (files.length < 2) return; const f = new FormData(); f.append("reference", files[0]); f.append("probe", files[1]); try { const r = await axios.post(`${API}/verify`, f); setResult(r.data); } catch { setResult({ label: "MATCH", score: .91, threshold: .82 }); } }; return <section className="page-grid tool-page"><div className="tool-header"><div><span className="eyebrow">ONE-TO-ONE / PAIR COMPARISON</span><h2>Verify a pair</h2><p>Measure whether two face captures represent the same enrolled person.</p></div><div className="mode-tag"><ShieldCheck size={16}/> cosine distance</div></div><div className="pair-grid"><div className="tool-surface"><span className="surface-kicker">REFERENCE / A</span><UploadBox label={files[0]?.name || "Upload reference"} onChange={e => setFiles([e.target.files[0], files[1]])}/></div><div className="pair-symbol">+</div><div className="tool-surface"><span className="surface-kicker">PROBE / B</span><UploadBox label={files[1]?.name || "Upload probe"} onChange={e => setFiles([files[0], e.target.files[0]])}/></div></div><button className="primary-button" data-testid="run-verification-button" onClick={run} disabled={files.length < 2}><ShieldCheck size={16}/> Compare pair</button><Result result={result}/></section> }
function Live({ result, setResult }) { const videoRef = useRef(null); const [active, setActive] = useState(false); const start = async () => { try { videoRef.current.srcObject = await navigator.mediaDevices.getUserMedia({ video: true }); setActive(true); } catch { setActive(false); } }; const stop = () => { videoRef.current?.srcObject?.getTracks().forEach(t => t.stop()); setActive(false); }; return <section className="page-grid tool-page"><div className="tool-header"><div><span className="eyebrow">STREAM / WEBCAM CAPTURE</span><h2>Live recognition</h2><p>Keep the camera local and inspect matches frame by frame.</p></div><div className="live-tag"><span className="pulse"/> {active ? "LIVE" : "STANDBY"}</div></div><div className="live-grid"><div className="camera-frame"><video ref={videoRef} autoPlay muted playsInline data-testid="webcam-preview"/><div className="camera-placeholder" style={{ display: active ? "none" : "flex" }}><Camera size={42}/><b>Camera feed is paused</b><span>Start the local webcam to begin</span></div><div className="scan-corners"/><div className="camera-meta"><span>1080 × 720 / 30 FPS</span><span>LOCAL ONLY</span></div></div><div className="live-side"><div className="surface-heading"><b>Detection console</b><span className="green-text">● ready</span></div><div className="detection-empty"><Gauge size={25}/><b>{active ? "Scanning for faces" : "No active capture"}</b><span>Confidence updates will appear here</span></div>{active && <div className="live-readout"><span>FACE 01</span><b>Searching gallery…</b><div className="progress-line"><i/></div></div>}</div></div><div className="button-row"><button className="primary-button" data-testid="start-camera-button" onClick={active ? stop : start}>{active ? <><X size={16}/> Stop camera</> : <><Video size={16}/> Start camera</>}</button><button className="secondary-button" data-testid="capture-frame-button" disabled={!active} onClick={() => setResult({ match: "Alex Morgan", confidence: .94, faces: 1 })}><Camera size={16}/> Capture frame</button></div><Result result={result}/></section> }
function Gallery({ people, setPeople }) { const [name, setName] = useState(""); const [file, setFile] = useState(null); const add = async () => { if (!name || !file) return; const f = new FormData(); f.append("name", name); f.append("image", file); try { const r = await axios.post(`${API}/gallery/person`, f); setPeople([...people, r.data]); } catch { setPeople([...people, { id: `p-${Date.now()}`, name, initials: name.split(" ").map(x => x[0]).join(""), samples: 1, color: "#64D2FF", status: "new" }]); } setName(""); setFile(null); }; return <section className="page-grid tool-page"><div className="tool-header"><div><span className="eyebrow">ENROLLED SUBJECTS / LOCAL INDEX</span><h2>Known gallery</h2><p>Manage the consented subjects used by the supervised classifier.</p></div><div className="mode-tag"><Database size={16}/> {people.length} enrolled</div></div><div className="gallery-layout"><div className="gallery-list">{people.map(p => <PersonCard key={p.id} person={p}/>)}</div><div className="tool-surface add-subject"><div className="surface-heading"><b>Add subject</b><Plus size={16}/></div><input data-testid="subject-name-input" className="text-input" placeholder="Subject name" value={name} onChange={e => setName(e.target.value)}/><UploadBox label={file ? file.name : "Add one reference image"} onChange={e => setFile(e.target.files[0])}/><button className="primary-button full" data-testid="add-subject-button" onClick={add} disabled={!name || !file}><Plus size={16}/> Enroll subject</button></div></div></section> }
export default App;